micronaut:
  application:
    name: helloWorld
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc
    driverClassName: org.postgresql.Driver
    username: rick
    password: password
#    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages: 'br.rcmto.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update

jackson:
  serialization:
    writeDatesAsTimestamps: false
